# Generated by Django 3.2.19 on 2023-09-11 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Administracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deportista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True, verbose_name='Nombre y Apellidos')),
                ('edad', models.PositiveIntegerField(null=True)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('estatura', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='pugiles')),
            ],
            options={
                'verbose_name': 'deportista',
                'verbose_name_plural': 'deportistas',
                'db_table': 'deportista',
            },
        ),
        migrations.CreateModel(
            name='Prueba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('archivo', models.FileField(upload_to='')),
                ('resultado', models.CharField(max_length=255)),
                ('observaciones', models.CharField(max_length=255)),
                ('valoracion', models.CharField(max_length=255)),
                ('deporte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Administracion.deporte')),
                ('deportista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Administracion.deportista')),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Administracion.evaluacion')),
                ('lugar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Administracion.lugar')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Administracion.servicios')),
            ],
            options={
                'verbose_name': 'prueba',
                'verbose_name_plural': 'pruebas',
                'db_table': 'prueba',
            },
        ),
        migrations.CreateModel(
            name='PruebaResultIndic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_ind', models.CharField(max_length=255)),
                ('indicador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Administracion.indicadores')),
                ('prueba', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Administracion.prueba')),
            ],
        ),
    ]
