# Generated by Django 3.2.19 on 2023-08-10 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Administracion', '0002_area_departamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicios',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Administracion.area'),
        ),
    ]
